
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  template: template0

development:
  <<: *default
  database: tt_app_development

test:
  <<: *default
  database: tt_app_test

production:
  <<: *default
  database: tt_app_production
  username: tt_app
  password: <%= ENV['TT_APP_DATABASE_PASSWORD'] %>
